version: "3.7"
services:
  redis:
    image: redis:alpine

  laravel-echo-server:
    image: mintopia/laravel-echo-server
    depends_on:
      - redis
    environment:
      LARAVEL_ECHO_SERVER_AUTH_HOST: http://nginx
      LARAVEL_ECHO_SERVER_HOST: 0.0.0.0
      LARAVEL_ECHO_SERVER_PORT: 6001
      ECHO_REDIS_HOST: redis
      ECHO_REDIS_PORT: 6379
      ECHO_PROTOCOL: http

  queue-worker:
    build:
      context: .
    command: php artisan queue:work --tries=3 --timeout=10
    depends_on:
      - redis
      - laravel-echo-server
    environment: &php_env
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8084
      APP_LOG: errorlog
      REDIS_HOST: redis
      BROADCAST_DRIVER: redis
      CACHE_DRIVER: redis
      QUEUE_DRIVER: redis
      ECHO_HOST_MODE: path

  php:
    build:
      context: .
    environment: *php_env

  nginx:
    build:
      context: nginx
    ports:
      - 8084:80
    depends_on:
      - php
      - laravel-echo-server
    environment:
      FASTCGI_PASS: php:9000
      LARAVEL_ECHO_SERVER_URL: http://laravel-echo-server:6001
